services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus2
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

# docker compose up to start